<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Soring,-searching,-and-counting" data-toc-modified-id="Soring,-searching,-and-counting-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Soring, searching, and counting</a></span><ul class="toc-item"><li><span><a href="#Sorting" data-toc-modified-id="Sorting-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Sorting</a></span></li><li><span><a href="#Searching" data-toc-modified-id="Searching-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Searching</a></span></li><li><span><a href="#Counting" data-toc-modified-id="Counting-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Counting</a></span></li></ul></li></ul></div>

# Soring, searching, and counting

In [270]:
import numpy as np

## Sorting

Q1. Sort x along the second axis.

In [271]:
x = np.array([[1,4],[3,1]])
np.sort(x)



array([[1, 4],
       [1, 3]])

Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [272]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
indices = np.lexsort((first_names, surnames))
indices


array([1, 2, 0], dtype=int64)

Q3. Get the indices that would sort x along the second axis.

In [273]:
x = np.array([[1,4],[3,1]])
np.argsort(x)

array([[0, 1],
       [1, 0]], dtype=int64)

Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [274]:
x = np.random.permutation(10)
print(x)
print(np.sort(x))

result_array = np.zeros_like(x, dtype=float)
result_array[4] = np.sort(x)[4]
result_array[:4] = x[:4] / x[:4]
result_array[5:] = x[5:] / x[5:]

result_array


[7 5 6 8 3 9 0 1 2 4]
[0 1 2 3 4 5 6 7 8 9]


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2332\1951406586.py:8: RuntimeWarning: invalid value encountered in divide
  result_array[5:] = x[5:] / x[5:]


array([ 1.,  1.,  1.,  1.,  4.,  1., nan,  1.,  1.,  1.])

Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

In [275]:
x = np.random.permutation(10)

indices = np.arange(10)
indices[2] = np.argsort(x)[2]
indices[:2] = indices[:2] / indices[:2]
indices[3:] = indices[3:] / indices[3:]

print(indices)

[-2147483648           1           9           1           1           1
           1           1           1           1]


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2332\3722287238.py:5: RuntimeWarning: invalid value encountered in divide
  indices[:2] = indices[:2] / indices[:2]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2332\3722287238.py:5: RuntimeWarning: invalid value encountered in cast
  indices[:2] = indices[:2] / indices[:2]


## Searching

Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [276]:
x = np.random.permutation(10).reshape(2, 5)

print(np.amax(x, axis=1))
print(np.amin(x, axis=1))
print(np.argmax(x, axis=1))
print(np.argmin(x, axis=1))

[9 8]
[0 3]
[4 2]
[1 4]


Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [277]:
x = np.array([[np.nan, 4], [3, 2]])

print(np.nanmax(x, axis=1))
print(np.nanmin(x, axis=1))

print(np.nanargmax(x, axis=1))
print(np.nanargmin(x, axis=1))

[4. 3.]
[4. 2.]
[1 0]
[1 1]


Q8. Get the values and indices of the elements that are bigger than 2 in x.


In [278]:
x = np.array([[1, 2, 3], [1, 3, 5]])

print(f'Значення {x[x > 2]}')
print(f'Індекси {np.argwhere(x > 2)}')

Значення [3 3 5]
Індекси [[0 2]
 [1 1]
 [1 2]]


Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [279]:
x = np.array([[1, 2, 3], [1, 3, 5]])

indices_greater_than_2 = np.where(x.flatten() > 2)
print(indices_greater_than_2)

(array([2, 4, 5], dtype=int64),)


Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [280]:
x = np.arange(-5, 4).reshape(3, 3)
print(np.where(x < 0, 0, x))


[[0 0 0]
 [0 0 0]
 [1 2 3]]


Q11. Get the indices where elements of y should be inserted to x to maintain order.

In [281]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]

np.searchsorted(x, y)


array([0, 2, 1, 3], dtype=int64)

## Counting

Q12. Get the number of nonzero elements in x.

In [282]:
x = [[0,1,7,0,0],[3,0,0,2,19]]

np.count_nonzero(x)

5